### ISSUE TITLE
①p17-p23の校正

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/algo-rl-ja#77]
# 担当
翻訳: @takayukisekine
校正: @YuriCat（担当者）

# 締切
- 追って記述

# TODO
詳しくは[wiki](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7)を参照

- [x] [①"pXX-pXXの校正"というIssueを切る](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#pxx-pxx%E3%81%AE%E6%A0%A1%E6%AD%A3%E3%81%A8%E3%81%84%E3%81%86issue%E3%82%92%E5%88%87%E3%82%8B)
- [ ] [②担当者が前回までの作業をGitHubに集約する](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#%E5%89%8D%E5%9B%9E%E3%81%BE%E3%81%A7%E3%81%AE%E4%BD%9C%E6%A5%AD%E3%82%92github%E3%81%AB%E9%9B%86%E7%B4%84%E3%81%99%E3%82%8B)
- [ ] [③担当者が訳を修正する](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#%E6%8B%85%E5%BD%93%E8%80%85%E3%81%8C%E8%A8%B3%E3%82%92%E4%BF%AE%E6%AD%A3%E3%81%99%E3%82%8B)
- [ ] [④担当者が皆のコメント・プルリクを踏まえ修正](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#%E6%8B%85%E5%BD%93%E8%80%85%E3%81%8C%E7%9A%86%E3%81%AE%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%92%E8%B8%8F%E3%81%BE%E3%81%88%E4%BF%AE%E6%AD%A3)
- [ ] [⑤勉強会で皆が修正をする](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#%E5%8B%89%E5%BC%B7%E4%BC%9A%E3%81%A7%E7%9A%86%E3%81%8C%E4%BF%AE%E6%AD%A3%E3%82%92%E3%81%99%E3%82%8B)
- [ ] [⑥担当者が勉強会での知見・コメントを踏まえ修正](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#%E6%8B%85%E5%BD%93%E8%80%85%E3%81%8C%E5%8B%89%E5%BC%B7%E4%BC%9A%E3%81%A7%E3%81%AE%E7%9F%A5%E8%A6%8B%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%82%92%E8%B8%8F%E3%81%BE%E3%81%88%E4%BF%AE%E6%AD%A3)
- [ ] [⑦@masomaticsによる校正](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#masomatics%E3%81%AB%E3%82%88%E3%82%8B%E6%A0%A1%E6%AD%A3)
- [ ] [⑧@maeyonによる校正](https://github.com/sotetsuk/algo-rl-ja/wiki/%E6%A0%A1%E6%AD%A3%E4%BD%9C%E6%A5%AD%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%90%84%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E4%BD%9C%E6%A5%AD%E4%B8%80%E8%A6%A7#maeyon%E3%81%AB%E3%82%88%E3%82%8B%E6%A0%A1%E6%AD%A3)
